name: Fetch BLS Data

on:
  schedule:
    - cron: '0 0 1 * *'  # Runs at midnight on the first day of each month
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t blaus-scripts .

    - name: Create output directory
      run: mkdir -p output

    - name: Run Docker container
      run: docker run --rm -v ${{ github.workspace }}/output:/app/output blaus-scripts

    - name: Upload CSVs as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: stateUnemployment
        path: output/stateUnemployment.csv

    - name: Upload county CSV as artifact
      uses: actions/upload-artifact@v3
      with:
        name: countyUnemployment
        path: output/countyUnemployment.csv

    - name: Upload place CSV as artifact
      uses: actions/upload-artifact@v3
      with:
        name: placeUnemployment
        path: output/placeUnemployment.csv
        
    - name: Upload merged CSV as artifact
      uses: actions/upload-artifact@v3
      with:
        name: Unemployment_data
        path: output/Unemployment_data.csv
